In [1]:
from distribution_fit_class import DistributionFit
from portfolio_optimization_class import PortfolioOptimization, optimize_windows
import pandas as pd
import numpy as np

In [2]:
distribution_fit = DistributionFit()
file_path = r'data\random_data\n_stocks_per_sector.csv'
distribution_fit.load_df_from_csv(file_path)

returns_df = pd.read_csv(r'data\random_data\n_stocks_per_sector.csv', index_col=0, parse_dates=True)

copulas = ["clayton_random", "gaussian", "t_student"]
distributions = ["gauss_dist", "t_dist"]
window_size = 32
taus = [0.0005, 0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.15, 0.2]
maximum_weight = 0.3

In [ ]:
for tau in taus:
    portfolios = optimize_windows(number_of_quarters=window_size, tau=tau, maximum_weight=maximum_weight, data_path=file_path)
    for copula in copulas:
        for window in range(0, 64):
            if window % 5 == 0:
                print(f'Tau: {tau}, Cop: {copula} - {window}')
            returns_window = returns_df.iloc[window : 32+window_size]
            distribution_fit = DistributionFit()
            distribution_fit.set_df(returns_window)
            distribution_fit.fit_distribution_all_stocks()
            # distribution_fit.get_fitted_params()
            simulated_data_path = r'../copulas_outputs/simulated_' + copula + '_22_stocks' + f'_{window}_window.csv'
            distribution_fit.load_simulated_data_from_csv(simulated_data_path)
            distribution_fit.calculate_returns_from_simulated_quantiles()
            returns_norm = distribution_fit.get_simulated_return_norm()
            returns_t = distribution_fit.get_simulated_return_t_student()

In [3]:
window = 5
output_file_path = r'../data_return_rates/simulated_' + copulas[0] + '_RETURNS_22_stocks' + f'_{window}_window_'


In [4]:
returns_norm = pd.read_csv(output_file_path + "gauss_dist.csv", index_col = 0)
returns_t = pd.read_csv(output_file_path + "t_dist.csv", index_col = 0)

In [5]:
returns_norm

CMI      JBHT       BDX       BIO      MSFT      SWKS       OMC  \
0      0.174667  0.201466  0.125107  0.275766  0.206327  0.331267  0.259702   
1      0.238237  0.099827  0.025140 -0.021074  0.115134  0.244453  0.125474   
2      0.098226  0.050624  0.105477 -0.014794  0.138216  0.009553  0.335068   
3      0.250413  0.070505 -0.041451  0.053312  0.156496 -0.013312  0.143283   
4      0.185395  0.052763  0.033829  0.159327  0.209534 -0.149455  0.214740   
...         ...       ...       ...       ...       ...       ...       ...   
99995  0.118538 -0.059755  0.028394  0.078856  0.118032 -0.070004  0.058689   
99996 -0.063348 -0.003809 -0.025038 -0.018172 -0.151827  0.046493 -0.274445   
99997 -0.096839  0.280233  0.110089  0.078124  0.090262  0.373896  0.143204   
99998  0.073677 -0.139334 -0.020350  0.155559  0.028368 -0.197021 -0.176733   
99999  0.297528  0.174859  0.057786  0.011591  0.001782 -0.045164  0.149693   

              T       TJX       LEG  ...      SPGI      SCHW       EMN  \
0      0.154890  0.233373  0.254577  ...  0.174249  0.153675  0.147786   
1      0.269675  0.144175 -0.083918  ...  0.173692  0.035565  0.001139   
2      0.008153  0.130328  0.206915  ...  0.193036 -0.032091  0.073009   
3      0.089362  0.175377  0.060369  ...  0.103781 -0.001588  0.119564   
4      0.118653  0.011118  0.247876  ...  0.177404  0.174572  0.214128   
...         ...       ...       ...  ...       ...       ...       ...   
99995 -0.097963 -0.045235 -0.089902  ... -0.128244 -0.279962  0.099956   
99996  0.048785 -0.160281 -0.218529  ... -0.014080 -0.183301 -0.220652   
99997  0.103051  0.015659  0.245086  ...  0.051642 -0.014863  0.332062   
99998  0.006283  0.042502  0.205778  ...  0.010748 -0.007200 -0.029494   
99999  0.141489  0.136381  0.004734  ...  0.030641  0.125729 -0.046166   

            PPG       FRT       MAA       CPB      MNST       OKE       CVX  
0      0.108542  0.140884  0.150621  0.090058  0.353677  0.054748  0.131697  
1      0.039719  0.112938  0.069717  0.068799  0.172014 -0.052388 -0.016217  
2     -0.108895  0.162891  0.010156 -0.087812  0.162380 -0.041426  0.202247  
3      0.117406  0.224702  0.115543  0.077675  0.049603  0.113270  0.027897  
4      0.271034  0.067654 -0.014293  0.069705  0.119468  0.085972  0.202039  
...         ...       ...       ...       ...       ...       ...       ...  
99995 -0.113454  0.006849  0.106023 -0.068759  0.020316  0.189773  0.021747  
99996 -0.072520 -0.127370  0.118739  0.026396 -0.170574  0.085745 -0.163845  
99997  0.000884 -0.045595  0.074354  0.019799  0.315262  0.140688  0.120229  
99998 -0.161330 -0.118704 -0.051126  0.034956 -0.012202  0.016364 -0.124995  
99999 -0.019266 -0.047866  0.010879  0.114385 -0.128642  0.202832  0.146355  

[100000 rows x 22 columns]

In [6]:
returns_window = returns_df.iloc[window : 32+window]

In [7]:
portfolios = optimize_windows(number_of_quarters=window_size, tau=0.01, maximum_weight=0.3, data_path=file_path)

In [8]:
portfolios

Start                       End  Number of quarters  \
0  2000-03-31 00:00:00+00:00 2007-12-31 00:00:00+00:00                  32   
1  2000-06-30 00:00:00+00:00 2008-03-31 00:00:00+00:00                  32   
2  2000-09-30 00:00:00+00:00 2008-06-30 00:00:00+00:00                  32   
3  2000-12-31 00:00:00+00:00 2008-09-30 00:00:00+00:00                  32   
4  2001-03-31 00:00:00+00:00 2008-12-31 00:00:00+00:00                  32   
..                       ...                       ...                 ...   
59 2014-12-31 00:00:00+00:00 2022-09-30 00:00:00+00:00                  32   
60 2015-03-31 00:00:00+00:00 2022-12-31 00:00:00+00:00                  32   
61 2015-06-30 00:00:00+00:00 2023-03-31 00:00:00+00:00                  32   
62 2015-09-30 00:00:00+00:00 2023-06-30 00:00:00+00:00                  32   
63 2015-12-31 00:00:00+00:00 2023-09-30 00:00:00+00:00                  32   

        EVAR  w0   w1        w2        w3   w4   w5  ...       w12  w13  w14  \
0  -0.007784   0  0.0  0.043773  0.143095  0.0  0.0  ...  0.176874    0    0   
1   0.008476   0  0.0  0.077527  0.258719  0.0  0.0  ...  0.000000    0    0   
2   0.008717   0  0.0  0.095292  0.245287  0.0  0.0  ...  0.000000    0    0   
3   0.019437   0  0.0  0.000000  0.212258  0.0  0.0  ...  0.000000    0    0   
4   0.019446   0  0.0  0.000000  0.211996  0.0  0.0  ...  0.000000    0    0   
..       ...  ..  ...       ...       ...  ...  ...  ...       ...  ...  ...   
59  0.085380   0  0.0  0.000000  0.000000  0.3  0.0  ...  0.184636    0    0   
60  0.085583   0  0.0  0.000000  0.000000  0.3  0.0  ...  0.186401    0    0   
61  0.085311   0  0.0  0.000000  0.000000  0.3  0.0  ...  0.184039    0    0   
62  0.085029   0  0.0  0.000000  0.000000  0.3  0.0  ...  0.181585    0    0   
63  0.084926   0  0.0  0.000000  0.000000  0.3  0.0  ...  0.180696    0    0   

    w15       w16       w17  w18       w19  w20       w21  
0   0.0  0.300000  0.134487  0.0  0.159032  0.0  0.000000  
1   0.0  0.300000  0.000000  0.0  0.034824  0.0  0.000000  
2   0.0  0.300000  0.000000  0.0  0.042239  0.0  0.000000  
3   0.0  0.161297  0.183153  0.0  0.000000  0.0  0.054263  
4   0.0  0.161751  0.182829  0.0  0.000000  0.0  0.054418  
..  ...       ...       ...  ...       ...  ...       ...  
59  0.0  0.000000  0.000000  0.3  0.032335  0.0  0.000000  
60  0.0  0.000000  0.000000  0.3  0.031499  0.0  0.000000  
61  0.0  0.000000  0.000000  0.3  0.032619  0.0  0.000000  
62  0.0  0.000000  0.000000  0.3  0.033782  0.0  0.000000  
63  0.0  0.000000  0.000000  0.3  0.034203  0.0  0.000000  

[64 rows x 26 columns]

In [9]:
weights = portfolios.iloc[window].filter(regex="^w\d+$").values
weights

array([0, 0.0, 0.17192001507198174, 0.09573200129569365, 0.0, 0.0,
       0.08559905784951555, 0.0, 0.0, 0, 0.002865479665235704, 0.0, 0.0,
       0, 0, 0.0, 0.0, 0.0, 0.0, 0.2736135185746489, 0.07026992754292442,
       0.3], dtype=object)

In [10]:
pd.DataFrame(returns_norm.values * weights)

0  1           2           3  4  5           6  7  8  9   ... 12 13 14  \
0      0  0   0.0215085   0.0263996  0  0   0.0222303  0  0  0  ...  0  0  0   
1      0  0  0.00432203 -0.00201743  0  0   0.0107404  0  0 -0  ...  0  0  0   
2      0  0   0.0181336 -0.00141623  0  0   0.0286815  0  0  0  ...  0 -0  0   
3      0  0 -0.00712623  0.00510369  0 -0   0.0122649  0  0  0  ...  0 -0  0   
4      0  0  0.00581589   0.0152527  0 -0   0.0183816  0  0  0  ...  0  0  0   
...   .. ..         ...         ... .. ..         ... .. .. ..  ... .. .. ..   
99995  0 -0  0.00488142  0.00754908  0 -0  0.00502374 -0 -0 -0  ... -0 -0  0   
99996 -0 -0 -0.00430452 -0.00173967 -0  0  -0.0234923  0 -0 -0  ... -0 -0 -0   
99997 -0  0   0.0189265  0.00747898  0  0   0.0122581  0  0  0  ...  0 -0  0   
99998  0 -0 -0.00349855    0.014892  0 -0  -0.0151282  0  0  0  ...  0 -0 -0   
99999  0  0   0.0099346  0.00110966  0 -0   0.0128136  0  0  0  ...  0  0 -0   

      15 16 17 18          19          20          21  
0      0  0  0  0   0.0967709  0.00384712   0.0395091  
1      0  0  0  0   0.0470654 -0.00368129 -0.00486505  
2     -0  0  0 -0   0.0444295 -0.00291101   0.0606741  
3      0  0  0  0   0.0135721  0.00795951  0.00836905  
4      0  0 -0  0   0.0326882  0.00604122   0.0606116  
...   .. .. .. ..         ...         ...         ...  
99995 -0  0  0 -0  0.00555869   0.0133354  0.00652417  
99996 -0 -0  0  0  -0.0466712  0.00602532  -0.0491536  
99997  0 -0  0  0   0.0862601  0.00988616   0.0360688  
99998 -0 -0 -0  0 -0.00333865  0.00114987  -0.0374985  
99999 -0 -0  0  0  -0.0351982    0.014253   0.0439064  

[100000 rows x 22 columns]

In [16]:
portfolio_returns = np.sum(returns_norm.values * weights, axis=1)
portfolio_returns

array([0.210323546726166, 0.051673883838015425, 0.1476524756355705, ...,
       0.1709558574793804, -0.043575110503820715, 0.04685125000438825],
      dtype=object)

In [11]:
pd.DataFrame(np.sum(returns_norm.values * weights, axis=1))

0
0       0.210324
1      0.0516739
2       0.147652
3      0.0404635
4       0.138892
...          ...
99995  0.0428438
99996  -0.119488
99997   0.170956
99998 -0.0435751
99999  0.0468513

[100000 rows x 1 columns]

In [15]:
expectile = -portfolios.iloc[window]["EVAR"]
expectile

-0.048521447033850494

In [19]:
tau = 0.01
validation_values = (1 - tau) * np.minimum(portfolio_returns - expectile, 0) - tau * np.maximum(portfolio_returns - expectile, 0)
validation_values

array([-0.0025884499376001647, -0.0010019533087186592,
       -0.00196173922669421, ..., -0.002194773045132309,
       -4.9463365300297794e-05, -0.0009537269703823875], dtype=object)

In [20]:
tau = 0.01
scoring_values = (1 - tau) * np.minimum((portfolio_returns - expectile)**2, 0) + tau * np.maximum((portfolio_returns - expectile)**2, 0)
scoring_values


array([0.0006700073079462296, 0.00010039104328522687,
       0.0003848420793550797, ..., 0.0004817028719639349,
       2.446624506830704e-07, 9.095951340347675e-05], dtype=object)

In [22]:
expected_validation_values = np.mean(validation_values)
expected_scoring_values = np.mean(scoring_values)

In [23]:
expected_validation_values

-0.00901387669080774